apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  - service.yaml
resources:
  - ../../../base/be
  - secret.yaml
images:
  - name: scgskku/icc-grad-dissertation-manage-backend
    newTag: dc1b27912824c5e0779af4c7dea77dc66b63ad76
