apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
- secret.yaml
images:
- name: scgskku/icc-grad-dissertation-manage-backend
  newTag: df93e11e8853f94597b1aac18af2e06c118fedb8
